[build]
  # Build command (none needed for static site)
  command = ""
  
  # Publish directory for the static site (root for GitHub Pages compatibility)
  publish = "."

[functions]
  # Directory containing Netlify Functions
  directory = "netlify/functions"
  
  # Use Node.js bundler for functions
  node_bundler = "esbuild"

# Redirect rules for frontend routing
[[redirects]]
  # Redirect /demo to the frontend demo page
  from = "/demo"
  to = "/frontend/index.html"
  status = 200

# Environment variables documentation
# Set these in your Netlify dashboard:
# GEMINI_API_KEY = your_google_gemini_api_key

# Build settings
[build.environment]
  # Node.js version for functions
  NODE_VERSION = "18"

# Function settings
[functions.gemini-proxy]
  # Timeout for the gemini-proxy function (max 30 seconds for hobby plan)
  timeout = 30